[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flash-alpadreams"
version = "0.1.0"
description = "Alpadreams inference with flashdreams"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flashdreams",
    "mediapy>=1.1",
    "ludus-renderer==0.5.0+cuda",
    "grpcio-tools",
    "grpcio",
    "opencv-python-headless",
    "shapely"
]

[tool.uv.sources]
flashdreams = { workspace = true }
ludus-renderer = { index = "flashdreams_pypi" }

[[tool.uv.index]]
name = "flashdreams_pypi"
url = "https://artifactory.nvidia.com/artifactory/api/pypi/oss-flashdreams-pypi-local/simple"
explicit = true

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-manual-marker",
]

[tool.setuptools.packages.find]
exclude = ["tests"]
