# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Options help descriptions keyed by canonical settings paths."""

OPTION_DESCRIPTIONS: dict[str, str] = {
    "diagnostics.profile_pipeline": "Enables pipeline profiling output.",
    "diagnostics.profile_input_latency": "Measures input-to-output latency.",
    "diagnostics.input_trace_path": "Optional file for input trace output.",
    "game.gamepad_button_style": "Labels shown for gamepad buttons: Xbox, PlayStation, or Nintendo Switch. It does not remap controls.",
    "game.taxi.seed": "Seed for repeatable taxi gameplay; blank uses fresh randomness. This is independent of the model diffusion seed.",
    "game.taxi.high_scores_path": "CSV file for the taxi leaderboard; blank uses the default high-score location.",
    "game.taxi.rules.waypoint_spacing_m": "Distance between candidate points sampled along navigation routes.",
    "game.taxi.rules.pickup_grid_spacing_m": "Spacing used to spread pickup locations across the map.",
    "game.taxi.rules.pickup_min_distance_m": "Minimum straight-line distance from the taxi to a new pickup.",
    "game.taxi.rules.initial_pickup_max_distance_m": "Preferred maximum distance to the first, camera-visible pickup.",
    "game.taxi.rules.pickup_radius_m": "Distance at which a passenger is collected.",
    "game.taxi.rules.dropoff_radius_m": "Distance at which a fare is completed.",
    "game.taxi.rules.fare_min_route_distance_m": "Preferred minimum route length from pickup to dropoff.",
    "game.taxi.rules.fare_max_route_distance_m": "Preferred maximum straight-line distance between fare endpoints. The minimum may not exceed this maximum.",
    "game.taxi.rules.target_speed_mps": "Nominal speed used to calculate a fare's time limit.",
    "game.taxi.rules.grace_s": "Extra time added to the distance-based fare limit.",
    "game.taxi.rules.min_time_s": "Lower bound for a fare's calculated time limit.",
    "game.taxi.rules.max_time_s": "Upper bound for a fare's calculated time limit; must be at least Min Time S.",
    "game.taxi.rules.trip_time_multiplier": "Multiplies the fare limit after it is calculated and clamped.",
    "game.taxi.rules.base_fare_points": "Points awarded for a completed fare.",
    "game.taxi.rules.bonus_points_per_second": "Additional points per whole second remaining on a completed fare.",
    "game.taxi.rules.event_banner_s": "Duration of pickup, completion, and failure banners in simulation time.",
    "game.taxi.rules.global_time_s": "Starting game clock; must be positive.",
    "game.taxi.rules.dropoff_time_bonus_s": "Time added to the game clock after a successful dropoff.",
    "game.taxi.rules.ground_snap_max_absolute_rotation_deg": "Largest ground rotation accepted when aligning the taxi to the road surface.",
    "game.taxi.rules.ground_snap_settle_fraction": "Fraction of stale ground attitude removed after an invalid ground sample.",
    "game.taxi.vehicle.wheel_base_m": "Distance between front and rear axles in the vehicle model.",
    "game.taxi.vehicle.max_steer_rad": "Maximum steering angle.",
    "game.taxi.vehicle.steer_rate_rad_per_s": "Rate at which steering moves toward full lock.",
    "game.taxi.vehicle.steer_return_rate_rad_per_s": "Rate at which steering recenters.",
    "game.taxi.vehicle.speed_limit_enabled": "Applies map speed limits to the taxi.",
    "game.taxi.vehicle.max_speed_mps": "Normal forward speed cap.",
    "game.taxi.vehicle.max_reverse_speed_mps": "Reverse speed cap.",
    "game.taxi.vehicle.max_accel_mps2": "Forward acceleration cap.",
    "game.taxi.vehicle.reverse_accel_mps2": "Reverse acceleration cap.",
    "game.taxi.vehicle.max_brake_mps2": "Normal braking strength.",
    "game.taxi.vehicle.handbrake_decel_mps2": "Deceleration while using the handbrake.",
    "game.taxi.vehicle.handbrake_yaw_gain": "Additional rotation induced by the handbrake.",
    "game.taxi.vehicle.max_handbrake_yaw_rate_radps": "Cap on handbrake rotation speed.",
    "game.taxi.vehicle.max_lateral_accel_mps2": "Lateral acceleration ceiling for steering and body response.",
    "game.taxi.vehicle.drag_mps2": "Base speed loss from drag.",
    "game.taxi.vehicle.mass_kg": "Vehicle mass used by the physical simulation.",
    "game.taxi.vehicle.tire_grip": "Tire traction factor.",
    "game.taxi.vehicle.rolling_resistance": "Resistance from rolling contact.",
    "game.taxi.vehicle.aero_drag_coefficient": "Aerodynamic drag factor.",
    "game.taxi.vehicle.collision_restitution": "General collision bounce.",
    "game.taxi.vehicle.collision_friction": "Friction during collisions.",
    "game.taxi.vehicle.max_collision_yaw_rate_radps": "Cap on rotation caused by collisions.",
    "game.taxi.vehicle.suspension_stiffness": "Suspension spring strength.",
    "game.taxi.vehicle.suspension_damping": "How quickly suspension motion settles.",
    "game.taxi.vehicle.suspension_travel_m": "Maximum suspension movement.",
    "game.taxi.vehicle.suspension_visual_gain": "Amount of visible suspension response.",
    "game.taxi.vehicle.max_body_roll_rad": "Limit on sideways body tilt.",
    "game.taxi.vehicle.max_body_pitch_rad": "Limit on forward/back body tilt.",
    "game.taxi.vehicle.actor_collision_enabled": "Enables collisions with dynamic actors.",
    "game.taxi.vehicle.static_collision_enabled": "Enables collisions with static map barriers.",
    "game.taxi.vehicle.aabb_length_m": "Length of the taxi's axis-aligned collision box.",
    "game.taxi.vehicle.aabb_width_m": "Width of the taxi's axis-aligned collision box.",
    "game.taxi.vehicle.aabb_height_m": "Height of the taxi's axis-aligned collision box.",
    "game.taxi.vehicle.curb_collision_restitution": "Bounce from curbs and other static barriers.",
    "game.taxi.vehicle.curb_forward_momentum_retention": "Minimum forward speed fraction retained after a glancing curb hit.",
    "game.taxi.vehicle.input_activation_threshold": "Smallest steering or pedal magnitude counted as active input.",
    "game.taxi.vehicle.direction_change_accel_multiplier": "Braking multiplier when switching travel direction.",
    "game.taxi.vehicle.speed_taper_knee_fraction": "Speed fraction where acceleration taper changes regime.",
    "game.taxi.vehicle.speed_taper_low_floor": "Minimum acceleration fraction below the speed-taper knee.",
    "game.taxi.vehicle.speed_taper_high_floor": "Minimum acceleration fraction above the speed-taper knee.",
    "game.taxi.vehicle.speed_taper_exponent": "How sharply acceleration falls above the knee.",
    "game.taxi.vehicle.manual_coast_decel_mps2": "Deceleration when neither pedal is pressed.",
    "game.taxi.vehicle.ragdoll_grip_rate": "Lateral velocity damping during collision recovery.",
    "game.taxi.vehicle.ragdoll_yaw_response_rate": "Rotation response during collision recovery.",
    "game.taxi.vehicle.handbrake_yaw_response_rate": "Rotation response while the handbrake is active.",
    "game.taxi.vehicle.handbrake_lateral_damping_rate": "Sideways velocity damping while the handbrake is active.",
    "game.taxi.vehicle.handbrake_lateral_accel_scale": "Body-roll acceleration scale with the handbrake.",
    "game.race.times_path": "File for race times; blank uses the default leaderboard location.",
    "game.effects.visual_flare": "Enables the game-directed visual flare effect.",
    "live_edit.sharpen_amount": "Unsharp-mask strength on styled frames; 0 disables sharpening.",
    "live_edit.sharpen_sigma": "Gaussian blur radius used by the unsharp mask.",
    "live_edit.perf_log_every_frames": "Interval for live-edit CPU/GPU cost reports; 0 disables them.",
    "live_edit.style.enabled": "Allows live skin switching.",
    "live_edit.style.lora_checkpoint": "Pre-merged text-edit LoRA used for skin swaps.",
    "live_edit.style.corrector_checkpoint": "Checkpoint for the style drift corrector.",
    "live_edit.style.corrector_gain": "Strength of the style drift corrector.",
    "live_edit.style.corrector_mode": "fused, unfused, or off deployment of the corrector.",
    "live_edit.style.base_corrector_checkpoint": "Optional corrector checkpoint for the base visual state.",
    "live_edit.style.base_corrector_gain": "Corrector strength for the base visual state.",
    "live_edit.style.gate_alpha_json": "Per-timestep corrector gate profile.",
    "live_edit.style.guidance_scale": "Guidance strength for a skin change.",
    "live_edit.style.guidance_chunks": "Number of chunks in the skin-change guidance window.",
    "live_edit.style.reswap_interval_chunks": "Reapplies the active skin every N chunks; 0 disables refresh.",
    "live_edit.style.skins": "List of selectable {name, prompt} skins. --live-edit-skin-first NAME only rotates the existing list.",
    "live_edit.coins.enabled": "Places collectible coins along lanes.",
    "live_edit.coins.spacing_m": "Distance between coin groups along the road.",
    "live_edit.coins.group_offsets_m": "Lateral positions of coins within a group.",
    "live_edit.coins.hover_height_m": "Height of coin centers above the road.",
    "live_edit.coins.coin_diameter_m": "World-space coin diameter used for rendering.",
    "live_edit.coins.pickup_radius_m": "Distance at which the taxi collects a coin.",
    "live_edit.coins.max_render_distance_m": "Coin visibility limit.",
    "live_edit.coins.fade_start_distance_m": "Distance where coins begin fading out.",
    "live_edit.coins.max_visible_sprites": "Per-frame cap, keeping nearest coins; 0 removes the cap.",
    "live_edit.coins.sprite_path": "Optional RGBA coin image; blank uses the procedural coin.",
    "live_edit.items.enabled": "Places collectible effect items along lanes.",
    "live_edit.items.spacing_m": "Distance between effect items along the road.",
    "live_edit.items.hover_height_m": "Height of effect items above the road.",
    "live_edit.items.item_diameter_m": "World-space item size used for rendering.",
    "live_edit.items.pickup_radius_m": "Distance at which the taxi collects an effect item.",
    "live_edit.items.max_render_distance_m": "Item visibility limit.",
    "live_edit.items.fade_start_distance_m": "Distance where items begin fading out.",
    "live_edit.items.rain_sprite_path": "Optional RGBA artwork for each item; blank uses a procedural placeholder.",
    "live_edit.items.snow_sprite_path": "Optional RGBA artwork for each item; blank uses a procedural placeholder.",
    "live_edit.items.mystery_sprite_path": "Optional RGBA artwork for each item; blank uses a procedural placeholder.",
    "live_edit.items.nitro_sprite_path": "Optional RGBA artwork for each item; blank uses a procedural placeholder.",
    "live_edit.items.item_types": "Mix of rain, snow, mystery, and nitro items placed on the course.",
    "live_edit.items.nitro_boost": "Multiplier applied to maximum speed while nitro is active.",
    "live_edit.items.nitro_duration_s": "Duration of a nitro boost in simulation time.",
    "live_edit.items.nitro_max_speed_mps": "Absolute cap on boosted maximum speed.",
    "live_edit.items.mystery_seed": "Repeatable mystery-item selection; blank uses fresh randomness.",
    "live_edit.items.flash_seconds": "Duration of the pickup notice on the HUD.",
    "live_edit.weather.enabled": "Allows live weather cycling.",
    "live_edit.weather.guidance_scale": "Strength of weather-change guidance; guided chunks run an extra model forward.",
    "live_edit.weather.guidance_chunks": "Number of guided chunks after changing weather.",
    "live_edit.weather.maintain_interval_chunks": "Chunks between optional weather-guidance refresh pulses; 0 disables them.",
    "live_edit.weather.maintain_chunks": "Guided chunks in each weather-guidance refresh pulse.",
    "live_edit.weather.clear_guidance_chunks": "Guided chunks used when changing back to clear weather.",
    "live_edit.weather.corrector_gain": "Strength of optional drift correction while weather is active.",
    "live_edit.weather.corrector_checkpoint": "Optional weather corrector checkpoint; blank reuses the style corrector.",
    "live_edit.weather.weathers": "List of selectable weather presets with names and prompt suffixes. --live-edit-weather-first NAME only rotates the existing list.",
    "live_edit.obstacle.enabled": "Enables obstacle spawn events.",
    "live_edit.obstacle.count": "Obstacle vehicles created by one spawn request.",
    "live_edit.obstacle.spacing_m": "Extra distance ahead for each additional obstacle vehicle.",
    "live_edit.obstacle.stagger_chunks": "Generated chunks between vehicles in one spawn request.",
    "live_edit.obstacle.spawn_ahead_m": "Distance ahead of the taxi for the first obstacle vehicle.",
    "live_edit.obstacle.lateral_m": "Sideways offset of spawned obstacles from the taxi heading.",
    "live_edit.obstacle.active_chunks": "Maximum generated chunks before a moving event despawns.",
    "live_edit.obstacle.min_drift_m": "Minimum displacement for a moving obstacle template.",
    "live_edit.obstacle.min_coverage_s": "Minimum duration of a moving obstacle source track.",
    "live_edit.obstacle.length_range_m": "Accepted vehicle-length range for obstacle templates.",
    "live_edit.obstacle.collision_radius_m": "Distance used to detect visual-only obstacle hits.",
    "live_edit.obstacle.physics": "Registers obstacles with the physical simulation.",
    "live_edit.obstacle.placement": "ego-relative or road-ahead placement.",
    "live_edit.obstacle.static_count": "Number of persistent roadblock cars placed at game start.",
    "live_edit.obstacle.static_ahead_m": "Distance ahead of the spawn pose for the first persistent car.",
    "live_edit.obstacle.static_lateral_m": "Sideways offset used for alternating persistent cars.",
    "live_edit.obstacle.guide_scale": "Box-conditioning guidance strength; 0 disables guidance. Guided event chunks do extra model work.",
    "live_edit.obstacle.annotate": "Draws projected obstacle boxes into presented frames.",
    "live_edit.map_context.enabled": "Adds authored road, landmark, topology, curve, and motion context to the model prompt.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.qkv_fusion_option": "How query, key, and value projections are fused.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.sdpa_backend": "Scaled dot-product attention kernel.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.use_tma": "Prefer TMA FlashAttention when supported.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.quantization.projection": "Optional Q/K/V projection precision; blank keeps native precision.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.quantization.output_projection": "Optional output projection precision; blank keeps native precision.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.quantization.output_granularity": "Granularity of output activation quantization.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.quantization.quantized_sdpa": "Casts attention Q/K/V to FP8 for the selected backend. This can affect accuracy.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.flex_attention.block_size": "Default square mask-block size.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.flex_attention.mask_block_m": "Optional query-side mask-block size.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.flex_attention.mask_block_n": "Optional key/value-side mask-block size.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.flex_attention.compile_dynamic": "Dynamic-shape compile policy.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.flex_attention.block_m": "Optional query-side kernel tile size.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.flex_attention.block_n": "Optional key/value-side kernel tile size.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.flex_attention.num_warps": "Optional Triton warp count.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.flex_attention.num_stages": "Optional Triton pipeline-stage count.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.flex_attention.prescale_qk": "Applies attention scale before the QK reduction.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.flex_attention.use_tma": "Requests TMA for FlexAttention; blank uses its default.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.flex_attention.backend": "Optional TRITON or FLASH FlexAttention kernel.",
    "model.pipeline.diffusion_model.transformer.network.self_attn_optimized_impl_config.flex_attention.rows_guaranteed_safe": "Skips empty-row guards when every query has a valid key.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.qkv_fusion_option": "How query, key, and value projections are fused.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.sdpa_backend": "Scaled dot-product attention kernel.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.use_tma": "Prefer TMA FlashAttention when supported.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.quantization.projection": "Optional Q/K/V projection precision; blank keeps native precision.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.quantization.output_projection": "Optional output projection precision; blank keeps native precision.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.quantization.output_granularity": "Granularity of output activation quantization.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.quantization.quantized_sdpa": "Casts attention Q/K/V to FP8 for the selected backend. This can affect accuracy.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.flex_attention.block_size": "Default square mask-block size.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.flex_attention.mask_block_m": "Optional query-side mask-block size.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.flex_attention.mask_block_n": "Optional key/value-side mask-block size.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.flex_attention.compile_dynamic": "Dynamic-shape compile policy.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.flex_attention.block_m": "Optional query-side kernel tile size.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.flex_attention.block_n": "Optional key/value-side kernel tile size.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.flex_attention.num_warps": "Optional Triton warp count.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.flex_attention.num_stages": "Optional Triton pipeline-stage count.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.flex_attention.prescale_qk": "Applies attention scale before the QK reduction.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.flex_attention.use_tma": "Requests TMA for FlexAttention; blank uses its default.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.flex_attention.backend": "Optional TRITON or FLASH FlexAttention kernel.",
    "model.pipeline.diffusion_model.transformer.network.cross_attn_optimized_impl_config.flex_attention.rows_guaranteed_safe": "Skips empty-row guards when every query has a valid key.",
    "model.pipeline.text_encoder.model_name": "Hugging Face model ID for Cosmos-Reason1.",
    "model.pipeline.text_encoder.revision": "Pinned model revision for Cosmos-Reason1.",
    "model.pipeline.text_encoder.max_length": "Text token limit, including padding and truncation.",
    "model.pipeline.text_encoder.dtype": "Parameter and activation precision of the text encoder.",
    "model.pipeline.text_encoder.embedding_concat_strategy": "How text layers are combined into embeddings.",
    "model.pipeline.text_encoder.n_layers_per_group": "Group size for grouped text-layer pooling.",
    "model.pipeline.text_encoder.run_on_cpu": "Keeps the text encoder on the host CPU to save GPU memory.",
    "model.pipeline.text_encoder.embedding_cache_size": "Number of previously encoded prompt batches retained; 0 disables caching.",
    "model.pipeline.image_encoder.checkpoint_path": "Checkpoint for the Wan VAE encoder.",
    "model.pipeline.image_encoder.dtype": "Parameter and activation precision of the Wan VAE encoder.",
    "model.pipeline.image_encoder.use_cuda_graph": "Enables CUDA graph replay for the VAE encoder.",
    "model.pipeline.image_encoder.use_compile": "Enables torch.compile for the VAE encoder.",
    "model.pipeline.image_encoder.base_dim": "Base VAE channel count; must match the checkpoint.",
    "model.pipeline.image_encoder.z_dim": "Latent channel count; must match the checkpoint.",
    "model.pipeline.image_encoder.patch_size": "Outer spatial patch factor; must match the checkpoint.",
    "model.pipeline.image_encoder.is_residual": "Selects the residual-block VAE architecture.",
    "model.pipeline.image_encoder.latent_mean": "Per-channel latent normalization mean.",
    "model.pipeline.image_encoder.latent_std": "Per-channel latent normalization standard deviation.",
    "model.pipeline.image_encoder.native_vae_acceleration": "Native VAE policy: disabled, auto, or required.",
    "model.pipeline.image_encoder.native_vae_build_root": "Native extension build and cache directory.",
    "model.pipeline.image_encoder.native_vae_max_jobs": "Parallel job cap for the native build.",
    "model.pipeline.image_encoder.native_vae_verbose_build": "Enables detailed native build logs.",
    "model.pipeline.image_encoder.native_vae_backend": "Native VAE compute backend, currently fp8.",
    "model.pipeline.image_encoder.native_vae_fp8_state_path": "File containing the exported FP8 VAE state.",
    "model.pipeline.image_encoder.native_vae_fp8_auto_export": "Automatically exports FP8 state when needed.",
    "model.pipeline.encoder.checkpoint_path": "Checkpoint for the Wan VAE encoder.",
    "model.pipeline.encoder.dtype": "Parameter and activation precision of the Wan VAE encoder.",
    "model.pipeline.encoder.use_cuda_graph": "Enables CUDA graph replay for the VAE encoder.",
    "model.pipeline.encoder.use_compile": "Enables torch.compile for the VAE encoder.",
    "model.pipeline.encoder.base_dim": "Base VAE channel count; must match the checkpoint.",
    "model.pipeline.encoder.z_dim": "Latent channel count; must match the checkpoint.",
    "model.pipeline.encoder.patch_size": "Outer spatial patch factor; must match the checkpoint.",
    "model.pipeline.encoder.is_residual": "Selects the residual-block VAE architecture.",
    "model.pipeline.encoder.latent_mean": "Per-channel latent normalization mean.",
    "model.pipeline.encoder.latent_std": "Per-channel latent normalization standard deviation.",
    "model.pipeline.encoder.native_vae_acceleration": "Native VAE policy: disabled, auto, or required.",
    "model.pipeline.encoder.native_vae_build_root": "Native extension build and cache directory.",
    "model.pipeline.encoder.native_vae_max_jobs": "Parallel job cap for the native build.",
    "model.pipeline.encoder.native_vae_verbose_build": "Enables detailed native build logs.",
    "model.pipeline.encoder.native_vae_backend": "Native VAE compute backend, currently fp8.",
    "model.pipeline.encoder.native_vae_fp8_state_path": "File containing the exported FP8 VAE state.",
    "model.pipeline.encoder.native_vae_fp8_auto_export": "Automatically exports FP8 state when needed.",
    "model.pipeline.decoder.checkpoint_path": "Checkpoint for the video decoder.",
    "model.pipeline.decoder.dtype": "Parameter and activation precision of the video decoder.",
    "model.pipeline.decoder.use_cuda_graph": "Enables CUDA graph replay for the video decoder.",
    "model.pipeline.decoder.use_compile": "Enables torch.compile for the video decoder.",
    "model.pipeline.diffusion_model.scheduler.num_inference_steps": "Number of denoising steps; must match the number of Denoising Timesteps.",
    "model.pipeline.diffusion_model.scheduler.denoising_timesteps": "Ordered model timesteps used for those steps.",
    "model.pipeline.diffusion_model.scheduler.shift": "Warping factor for the noise schedule.",
    "model.pipeline.diffusion_model.scheduler.warp_denoising_step": "Applies that warped schedule to the listed timesteps.",
    "model.pipeline.diffusion_model.scheduler.num_train_timesteps": "Length of the training timestep scale.",
    "model.pipeline.diffusion_model.scheduler.sigma_max": "Upper end of the noise schedule before warping.",
    "model.pipeline.diffusion_model.scheduler.sigma_min": "Lower end of the noise schedule before warping.",
    "model.pipeline.diffusion_model.scheduler.extra_one_step": "Builds the schedule using one extra sample, then drops the last.",
    "model.pipeline.diffusion_model.scheduler.timestep_dtype": "Numeric type passed to the model time embedding.",
    "model.pipeline.diffusion_model.scheduler.enable_tqdm": "Shows scheduler progress output.",
    "model.pipeline.diffusion_model.transformer.dtype": "Parameter and activation precision.",
    "model.pipeline.diffusion_model.transformer.checkpoint_path": "Pretrained transformer weights.",
    "model.pipeline.diffusion_model.transformer.batch_shape": "Batch dimensions of the generated latent.",
    "model.pipeline.diffusion_model.transformer.num_views": "Number of camera views.",
    "model.pipeline.diffusion_model.transformer.len_t": "Latent frames generated per chunk.",
    "model.pipeline.diffusion_model.transformer.h_extrapolation_ratio": "Height RoPE extrapolation factor.",
    "model.pipeline.diffusion_model.transformer.w_extrapolation_ratio": "Width RoPE extrapolation factor.",
    "model.pipeline.diffusion_model.transformer.window_size_t": "Sliding self-attention history in temporal units before patchification.",
    "model.pipeline.diffusion_model.transformer.sink_size_t": "Temporal sink tokens retained in attention history.",
    "model.pipeline.diffusion_model.transformer.early_short_history_block_count": "Number of first blocks limited to one chunk of visual history; blank disables this policy.",
    "model.pipeline.diffusion_model.transformer.compile_network": "Uses torch.compile for the network.",
    "model.pipeline.diffusion_model.transformer.use_cuda_graph": "Captures and replays steady-state model work in a CUDA graph.",
    "model.pipeline.diffusion_model.transformer.cuda_graph_warmup_iters": "Eager warmup calls before graph capture.",
    "model.pipeline.diffusion_model.transformer.skip_finalize_kv_cache": "Skips the separate cache-finalization pass.",
    "model.pipeline.diffusion_model.transformer.native_dit_acceleration": "Native DiT policy: disabled, auto, or required.",
    "model.pipeline.diffusion_model.transformer.native_dit_build_root": "Native extension build and cache location.",
    "model.pipeline.diffusion_model.transformer.native_dit_max_jobs": "Parallel job cap for the native extension build.",
    "model.pipeline.diffusion_model.transformer.native_dit_verbose_build": "Enables detailed native extension build logs.",
    "model.pipeline.diffusion_model.transformer.native_dit_backend": "Native compute backend, fp8_kvcache_cudnn or bf16.",
    "model.pipeline.diffusion_model.transformer.native_dit_attention_backend": "Native attention implementation (auto, cuDNN/Sage/Sparge policies supported by the runtime).",
    "model.pipeline.diffusion_model.transformer.native_dit_sparge_topk": "Top-k selection ratio for Sparge sparse attention.",
    "model.pipeline.diffusion_model.transformer.native_dit_sparge_hybrid_period": "Period of a Sparge and SageAttention hybrid schedule.",
    "model.pipeline.diffusion_model.transformer.native_dit_sparge_hybrid_phase": "Phase offset for the hybrid sparse-attention schedule.",
    "model.pipeline.diffusion_model.transformer.guidance_scale": "Classifier-free guidance strength; 1 disables it. Higher values require negative text embeddings.",
    "model.pipeline.diffusion_model.transformer.network.in_channels": "Number of input latent channels.",
    "model.pipeline.diffusion_model.transformer.network.out_channels": "Number of output latent channels.",
    "model.pipeline.diffusion_model.transformer.network.patch_spatial": "Spatial patch size for height and width.",
    "model.pipeline.diffusion_model.transformer.network.patch_temporal": "Temporal patch size.",
    "model.pipeline.diffusion_model.transformer.network.model_channels": "Transformer hidden width.",
    "model.pipeline.diffusion_model.transformer.network.num_blocks": "Number of transformer blocks.",
    "model.pipeline.diffusion_model.transformer.network.num_heads": "Number of attention heads.",
    "model.pipeline.diffusion_model.transformer.network.mlp_ratio": "Feed-forward width relative to hidden width.",
    "model.pipeline.diffusion_model.transformer.network.concat_padding_mask": "Adds a padding-mask input channel.",
    "model.pipeline.diffusion_model.transformer.network.use_adaln_lora": "Enables low-rank adaptive layer normalization.",
    "model.pipeline.diffusion_model.transformer.network.adaln_lora_dim": "Rank of the adaptive layer normalization LoRA.",
    "model.pipeline.diffusion_model.transformer.network.use_crossattn_projection": "Projects text embeddings before cross-attention.",
    "model.pipeline.diffusion_model.transformer.network.crossattn_proj_in_channels": "Input width of the text embedding projection.",
    "model.pipeline.diffusion_model.transformer.network.crossattn_emb_channels": "Key and value width for cross-attention.",
    "model.pipeline.diffusion_model.transformer.network.timestep_scale": "Multiplier applied before timestep embedding.",
    "model.pipeline.diffusion_model.transformer.network.apply_rope_before_kvcache": "Rotates keys before caching; off uses cache-relative RoPE.",
    "model.pipeline.diffusion_model.transformer.network.additional_concat_ch": "Extra channels for HD-map conditioning; zero disables that input.",
    "model.pipeline.diffusion_model.transformer.network.enable_cross_view_attn": "Enables multi-view attention and view modulation.",
    "model.pipeline.diffusion_model.transformer.network.cp_method": "Context-parallel attention method: ring or ulysses.",
    "model.pipeline.diffusion_model.transformer.network.self_attention_backend": "Implementation used by transformer self-attention.",
    "model.pipeline.diffusion_model.transformer.network.cross_attention_backend": "Implementation used by text and cross-view attention.",
    "model.pipeline.diffusion_model.transformer.network.view_condition_dim": "Width of the view-conditioning vector.",
    "model.pipeline.diffusion_model.transformer.network.n_cameras_emb": "Number of camera-view embeddings.",
    "model.device": "Device used for the world model, normally cuda.",
    "model.pipeline.synthetic_text_max_length": "Token count for synthetic latency measurements; blank for real runs.",
    "model.pipeline.diffusion_model.seed": "Seed for initial model noise and scheduler sampling; blank uses the global RNG.",
    "model.pipeline.diffusion_model.context_noise": "Timestep used when updating the autoregressive cache; 0 skips added noise.",
    "model.pipeline.diffusion_model.noise_in_unpatchified_shape": "Debug option that draws noise before patchifying to match another implementation's random sequence.",
    "presentation.width": "Display width in pixels; blank uses the model width. Set with Height.",
    "presentation.height": "Display height in pixels; blank uses the model height. Set with Width.",
    "presentation.hud_enabled": "Shows the gameplay HUD.",
    "presentation.show_fps": "Shows the frame-rate counter.",
    "presentation.show_current_prompt": "Shows the world-model prompt.",
    "presentation.show_control_hints": "Shows the control help on the HUD.",
    "presentation.show_live_edit_buttons": "Shows live-edit ability buttons.",
    "presentation.live_edit_mapping_location": "Places live-edit mappings in buttons or control hints.",
    "renderer.raster.width": "Main raster width in pixels; must be positive.",
    "renderer.raster.height": "Main raster height in pixels; must be positive.",
    "renderer.raster.compute_device": "Device used for raster computation.",
    "renderer.raster.sync_gpu_timing": "Synchronizes GPU work for timing measurements.",
    "renderer.raster.perf_log_interval_frames": "Interval for raster performance logs.",
    "renderer.raster.near_plane_m": "Nearest camera clipping distance; must be less than Far Plane M.",
    "renderer.raster.far_plane_m": "Farthest camera clipping distance; must exceed Near Plane M.",
    "renderer.raster.fog_start_m": "Distance where fog begins; must be less than Fog End M.",
    "renderer.raster.fog_end_m": "Distance where fog reaches full strength; must exceed Fog Start M.",
    "renderer.raster.fog_power": "Exponent controlling the fog transition curve.",
    "renderer.raster.triangle_raytrace_distance_m": "Maximum distance for triangle ray tracing.",
    "renderer.raster.triangle_raytrace_edge_samples": "Number of edge samples for triangle ray tracing.",
    "renderer.raster.lane_segment_interval_m": "Segment spacing when rasterizing lanes.",
    "renderer.raster.polyline_segment_interval_m": "Segment spacing when rasterizing other polylines.",
    "renderer.raster.line_width_px": "Rendered road-line width in pixels.",
    "renderer.raster.pole_width_px": "Rendered pole width in pixels.",
    "renderer.raster.dual_line_offset_m": "Separation of paired road lines.",
    "renderer.raster.depth_clear_m": "Initial depth-buffer distance.",
    "renderer.bev.enabled": "Displays the top-down view.",
    "renderer.bev.width": "Top-down image width in pixels; must be positive.",
    "renderer.bev.height": "Top-down image height in pixels; must be positive.",
    "renderer.bev.height_m": "Camera height above the scene; must be positive.",
    "renderer.bev.fov_deg": "Top-down camera field of view in degrees.",
    "renderer.bev.tilt_deg": "Top-down camera tilt in degrees.",
    "runtime.total_blocks": "Optional limit on generated model blocks; blank leaves the run unbounded.",
    "runtime.prewarm_blocks": "Blocks generated before play to warm the pipeline; must be nonnegative.",
}
"""Plain-text help for the settings documented in the Options guides."""
