# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Runtime V2 transformer adapter for the released LongSana generator."""

from __future__ import annotations

import gc
import time
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Any, cast

import torch
import torch.nn as nn
from loguru import logger
from torch import Tensor

from flashdreams.core.checkpoint.load import load_checkpoint
from flashdreams.infra.compile import compile_module
from flashdreams.infra.diffusion.transformer import (
    Transformer,
    TransformerAutoregressiveCache,
    TransformerConfig,
)
from longsana.impl.constants import (
    DEFAULT_VIDEO_HEIGHT,
    DEFAULT_VIDEO_WIDTH,
    FIRST_LATENT_BLOCK_FRAMES,
    LATENT_BLOCK_FRAMES,
    LONGSANA_CHECKPOINT_PATH,
)
from longsana.impl.model import (
    LongSanaBlockState,
    LongSanaModel,
    LongSanaNetworkConfig,
)


@dataclass(kw_only=True)
class LongSanaConditioning:
    """Static positive-prompt inputs for one LongSana rollout."""

    condition: Tensor
    """Gemma prompt features shaped [B, 1, L, 2304]."""

    mask: Tensor
    """Valid-token mask shaped [B, L]."""


@dataclass(kw_only=True)
class LongSanaTransformerCache(TransformerAutoregressiveCache):
    """Prompt and constant-memory block state for one LongSana rollout."""

    conditioning: LongSanaConditioning | None = None
    """Static prompt conditioning."""

    block_states: list[LongSanaBlockState] = field(default_factory=list)
    """One three-tensor recurrent state per transformer block."""

    first_block_frames: int = FIRST_LATENT_BLOCK_FRAMES
    """Latent frames generated by AR step zero."""

    block_frames: int = LATENT_BLOCK_FRAMES
    """Latent frames generated by every later AR step."""

    projected_condition: Tensor | None = None
    """Prompt projection cached after its first model use."""

    start_frame: int = 0
    """Absolute latent-frame position of the active block."""

    next_index: int = 0
    """Next legal autoregressive index."""

    active_index: int | None = None
    """Currently-generating index, cleared by finalize."""

    active_frames: int = 0
    """Latent-frame count of the active block."""

    def start(self, autoregressive_index: int) -> None:
        """Validate and mark the start of the next LongSana block."""
        if self.active_index is not None:
            raise RuntimeError(
                f"LongSana AR step {self.active_index} has not been finalized."
            )
        if autoregressive_index != self.next_index:
            raise ValueError(
                f"Expected LongSana AR step {self.next_index}, "
                f"got {autoregressive_index}."
            )
        self.active_index = autoregressive_index
        self.active_frames = (
            self.first_block_frames if autoregressive_index == 0 else self.block_frames
        )

    def finalize(self, autoregressive_index: int) -> None:
        """Advance absolute positions after the clean-timestep cache update."""
        if self.active_index != autoregressive_index:
            raise ValueError(
                f"Active LongSana AR step is {self.active_index}, "
                f"cannot finalize {autoregressive_index}."
            )
        self.start_frame += self.active_frames
        self.next_index += 1
        self.active_index = None
        self.active_frames = 0

    def state_bytes(self) -> int:
        """Return recurrent block-state bytes, excluding static prompt tensors."""
        return sum(state.num_bytes() for state in self.block_states)


@dataclass(kw_only=True)
class LongSanaTransformerConfig(TransformerConfig):
    """Config for the Runtime V2 LongSana transformer."""

    _target: type["LongSanaTransformer"] = field(
        default_factory=lambda: LongSanaTransformer
    )

    network: LongSanaNetworkConfig = field(default_factory=LongSanaNetworkConfig)
    """Checkpoint-facing LongSana network architecture."""

    checkpoint_path: str = LONGSANA_CHECKPOINT_PATH
    """Public self-forcing checkpoint path or Hugging Face file URL."""

    dtype: torch.dtype = torch.bfloat16
    """Generator parameter and activation dtype."""

    latent_height: int = DEFAULT_VIDEO_HEIGHT // 8
    """Wan-latent height."""

    latent_width: int = DEFAULT_VIDEO_WIDTH // 8
    """Wan-latent width."""

    first_block_frames: int = FIRST_LATENT_BLOCK_FRAMES
    """Latent frames in AR step zero."""

    block_frames: int = LATENT_BLOCK_FRAMES
    """Latent frames in each later AR step."""

    compile_network: bool = False
    """Compile the DiT after strict checkpoint loading."""


class LongSanaTransformer(Transformer[LongSanaTransformerCache]):
    """Lazy-loading Runtime V2 adapter for LongSana flow prediction."""

    config: LongSanaTransformerConfig

    def __init__(self, config: LongSanaTransformerConfig) -> None:
        super().__init__(config)
        self.config = config
        self._dummy = nn.Parameter(torch.empty(0, dtype=config.dtype))
        self._model_built = False
        self._active_autoregressive_index = 0

    @property
    def latent_shape(self) -> tuple[int, ...]:
        """Return the raw Wan latent shape for the selected AR block."""
        frames = (
            self.config.first_block_frames
            if self._active_autoregressive_index == 0
            else self.config.block_frames
        )
        return (
            frames,
            self.config.network.spec.latent_channels,
            self.config.latent_height,
            self.config.latent_width,
        )

    def select_autoregressive_index(self, autoregressive_index: int) -> None:
        """Select the block shape before Runtime V2 allocates initial noise."""
        if autoregressive_index < 0:
            raise ValueError("LongSana autoregressive_index must be non-negative.")
        self._active_autoregressive_index = autoregressive_index

    def initialize_autoregressive_cache(
        self,
        *,
        conditioning: LongSanaConditioning | None = None,
        **_: Any,
    ) -> LongSanaTransformerCache:
        """Create a prompt cache and empty constant-memory state."""
        return LongSanaTransformerCache(
            conditioning=conditioning,
            block_states=[
                LongSanaBlockState() for _ in range(self.config.network.spec.depth)
            ],
            first_block_frames=self.config.first_block_frames,
            block_frames=self.config.block_frames,
        )

    def initial_noise(
        self,
        *,
        latent_shape: tuple[int, ...],
        rng: torch.Generator | None,
        cache: LongSanaTransformerCache,
        input: Any = None,
    ) -> Tensor:
        """Draw upstream B/C/T/H/W noise and expose it as Runtime V2 T/C/H/W."""
        del cache, input
        frames, channels, height, width = latent_shape
        noise = torch.randn(
            (channels, frames, height, width),
            device=self.device,
            dtype=self.dtype,
            generator=rng,
        )
        return noise.permute(1, 0, 2, 3).contiguous()

    def predict_flow(
        self,
        noisy_latent: Tensor,
        timestep: Tensor,
        cache: LongSanaTransformerCache,
        input: Any = None,
    ) -> Tensor:
        """Predict flow without mutating the recurrent LongSana state."""
        if input is not None:
            raise ValueError("LongSana T2V does not accept a per-block encoder input.")
        return self._predict(
            noisy_latent=noisy_latent,
            timestep=timestep,
            cache=cache,
            update_state=False,
        )

    def finalize_kv_cache(
        self,
        noisy_latent: Tensor,
        timestep: Tensor,
        cache: LongSanaTransformerCache,
        input: Any = None,
    ) -> None:
        """Commit the clean block using LongSana's required zero-step forward."""
        if input is not None:
            raise ValueError("LongSana T2V does not accept a per-block encoder input.")
        _ = self._predict(
            noisy_latent=noisy_latent,
            timestep=timestep,
            cache=cache,
            update_state=True,
        )

    def patchify_and_maybe_split_cp(self, x: Any) -> Any:
        """Keep Wan latents in raw BCTHW layout; the DiT owns patch embedding."""
        return x

    def unpatchify_and_maybe_gather_cp(self, x: Tensor) -> Tensor:
        """Return raw BCTHW latents unchanged."""
        return x

    def release_runtime(self) -> None:
        """Release loaded generator weights and CUDA caching allocations."""
        if hasattr(self, "model"):
            del self.model
        self._model_built = False
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    def _predict(
        self,
        *,
        noisy_latent: Tensor,
        timestep: Tensor,
        cache: LongSanaTransformerCache,
        update_state: bool,
    ) -> Tensor:
        conditioning = cache.conditioning
        if conditioning is None:
            raise RuntimeError("LongSana cache was initialized without a text prompt.")
        if cache.active_index is None:
            raise RuntimeError(
                "LongSana flow prediction ran outside an active AR step."
            )
        self._ensure_model()
        model = cast(LongSanaModel, self.model)
        if cache.projected_condition is None:
            cache.projected_condition = model.prepare_condition(
                conditioning.condition.to(device=self.device)
            )
        add_batch = noisy_latent.ndim == 4
        model_input = (
            noisy_latent.permute(1, 0, 2, 3).unsqueeze(0).contiguous()
            if add_batch
            else noisy_latent
        )
        output = model(
            model_input,
            timestep,
            cache.projected_condition,
            conditioning.mask,
            cache.block_states,
            start_frame=cache.start_frame,
            update_state=update_state,
        )
        return (
            output.squeeze(0).permute(1, 0, 2, 3).contiguous() if add_batch else output
        )

    def _ensure_model(self) -> None:
        if self._model_built:
            return
        started = time.perf_counter()
        with torch.device(self.device):
            model = self.config.network.setup()
        model = model.to(dtype=self.config.dtype)
        logger.info(
            "[LongSana] Built {} ({:,} parameters)",
            type(model).__name__,
            sum(parameter.numel() for parameter in model.parameters()),
        )

        payload = load_checkpoint(self.config.checkpoint_path)
        state_dict = longsana_state_dict(payload)
        model.load_state_dict(state_dict, strict=True)
        del payload, state_dict
        gc.collect()

        model = model.eval()
        if self.config.compile_network:
            model = compile_module(model)
        self.model = model
        self._model_built = True
        logger.info(
            "[timing] LongSana generator build+load: {:.3f}s (dtype={})",
            time.perf_counter() - started,
            self.config.dtype,
        )


def longsana_state_dict(payload: Any) -> dict[str, Tensor]:
    """Extract generator.model tensors from the public training checkpoint."""
    if not isinstance(payload, Mapping):
        raise TypeError(
            f"LongSana checkpoint must be a mapping, got {type(payload).__name__}."
        )
    state: Any = payload.get("generator", payload)
    if isinstance(state, Mapping):
        state = state.get("state_dict", state)
    if not isinstance(state, Mapping):
        raise TypeError(
            "LongSana checkpoint generator/state_dict entry must be a mapping."
        )

    model_prefix = "model."
    prefixed = {
        str(key)[len(model_prefix) :]: value
        for key, value in state.items()
        if str(key).startswith(model_prefix) and isinstance(value, Tensor)
    }
    if prefixed:
        return prefixed
    return {
        str(key): value for key, value in state.items() if isinstance(value, Tensor)
    }


def checkpoint_tensor_bytes(state_dict: Mapping[str, Tensor]) -> int:
    """Return total tensor bytes in a normalized LongSana state dict."""
    return sum(tensor.numel() * tensor.element_size() for tensor in state_dict.values())
