# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Experimental shared demo API above the inference runtime API."""

from flashdreams.runtime.demo.drivers import (
    CLEANUP_TIMEOUT_S,
    BatchSessionDriver,
    DriverInvariantError,
    RealtimeSessionDriver,
    run_demo_session,
    run_demo_session_async,
    shielded_session_cleanup,
    uncancel_current_task,
)
from flashdreams.runtime.demo.host import (
    ModelWarmupPlan,
    RuntimeHost,
    WarmupSessionInputs,
)
from flashdreams.runtime.demo.outputs import (
    Mp4OutputSink,
    NullOutputSink,
    OutputDecision,
    OutputSink,
    SessionInfo,
    build_output_sink,
    build_output_target,
)
from flashdreams.runtime.demo.pipeline import StepOutcome, StepPipeline
from flashdreams.runtime.demo.replay import run_replay_demo
from flashdreams.runtime.demo.run_modes import (
    AsyncSessionDriver,
    DefaultErrorPolicy,
    ErrorAction,
    InMemorySessionMetricsRecorder,
    MetricsSnapshot,
    NoopTransportService,
    RunContext,
    RunMode,
    RunModeWarmup,
    RunResult,
    RunSummary,
    SessionDriver,
    SessionEdges,
    SingleSessionAdmissionPolicy,
)
from flashdreams.runtime.demo.session_inputs import (
    BatchInputSource,
    ControlDecision,
    InputSource,
    ModelInputProvider,
    PreparedStep,
    RealtimeInputSource,
    UserInputWindow,
)
from flashdreams.runtime.demo.spec import (
    DemoAdapter,
    DemoSpec,
    Mp4OutputSpec,
    NullOutputSpec,
    OutputSpec,
    PreparedScenario,
    WebRTCAppResources,
    WebRTCOutputSpec,
)
from flashdreams.runtime.demo.timing import (
    SPARSE_KEY_SEGMENTS_METADATA_KEY,
    ActivationPolicy,
    ActivationResult,
    ActivationSignal,
    AlwaysActiveActivationPolicy,
    CatchUpDecision,
    CatchUpPolicy,
    DeterministicClock,
    KeyboardRealtimeInputSource,
    RealtimeClock,
    RealtimeWindowResult,
    ResamplerRealtimeClock,
    SignalActivationPolicy,
    input_frame_count_from_request,
)

__all__ = [
    "BatchInputSource",
    "BatchSessionDriver",
    "CLEANUP_TIMEOUT_S",
    "ControlDecision",
    "DefaultErrorPolicy",
    "DemoAdapter",
    "DemoSpec",
    "DriverInvariantError",
    "ErrorAction",
    "AsyncSessionDriver",
    "ActivationPolicy",
    "ActivationResult",
    "ActivationSignal",
    "AlwaysActiveActivationPolicy",
    "InMemorySessionMetricsRecorder",
    "InputSource",
    "CatchUpDecision",
    "CatchUpPolicy",
    "DeterministicClock",
    "MetricsSnapshot",
    "ModelWarmupPlan",
    "ModelInputProvider",
    "KeyboardRealtimeInputSource",
    "Mp4OutputSink",
    "Mp4OutputSpec",
    "NoopTransportService",
    "NullOutputSpec",
    "NullOutputSink",
    "OutputDecision",
    "OutputSpec",
    "OutputSink",
    "PreparedScenario",
    "PreparedStep",
    "RealtimeInputSource",
    "RealtimeClock",
    "RealtimeSessionDriver",
    "RealtimeWindowResult",
    "ResamplerRealtimeClock",
    "RunContext",
    "RunMode",
    "RunModeWarmup",
    "RunResult",
    "RunSummary",
    "RuntimeHost",
    "SessionEdges",
    "SessionDriver",
    "SessionInfo",
    "SignalActivationPolicy",
    "SingleSessionAdmissionPolicy",
    "SPARSE_KEY_SEGMENTS_METADATA_KEY",
    "StepOutcome",
    "StepPipeline",
    "UserInputWindow",
    "WarmupSessionInputs",
    "WebRTCAppResources",
    "WebRTCOutputSpec",
    "build_output_sink",
    "build_output_target",
    "input_frame_count_from_request",
    "run_demo_session",
    "run_demo_session_async",
    "run_replay_demo",
    "shielded_session_cleanup",
    "uncancel_current_task",
]
