# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Headless Omnidreams application with HDMap input and video output."""

from __future__ import annotations

import argparse
import copy
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Generic, TypeVar

import torch
from flashdreams.infra.runner_io import (
    DEFAULT_RUNNER_INSTALL_HINT,
    load_first_frame_tensor,
)
from flashdreams.runtime.application import ApplicationConfig
from flashdreams.runtime.builtin.application.video_output_application import (
    VideoOutputApplication,
    VideoOutputApplicationConfig,
)
from flashdreams.runtime.global_condition import GlobalConditionHandler
from flashdreams.runtime.inference_runtime import (
    InferenceRuntime,
    InferenceRuntimeConfig,
)
from flashdreams.runtime.input_system import UserInputHandler
from omnidreams.config import OMNIDREAMS_CONFIGS
from omnidreams.constants import NEGATIVE_PROMPT
from omnidreams.pipeline import OmnidreamsPipeline
from omnidreams.runtime.global_condition import (
    GlobalConditionHandler as OmnidreamsGlobalConditionHandler,
)
from omnidreams.runtime.global_condition import RawGlobalCondition
from omnidreams.runtime.inference_session import (
    InferenceGlobalCondition,
    InferenceSession,
)
from omnidreams.runtime.user_input.hdmap_input_handler import HDMapInputHandler
from omnidreams.transformer import CosmosTransformerConfig

RuntimeT = TypeVar("RuntimeT", bound=InferenceRuntime)
"""Inference-runtime type owned by the headless application."""

DEFAULT_TEXT_PROMPT = (
    "Driving scene from a front-facing car camera. Urban environment with roads, "
    "vehicles, pedestrians, traffic signs, and buildings. Clear visibility, "
    "realistic lighting, photorealistic quality. High resolution dashcam footage "
    "of city driving."
)
"""Default positive prompt for a single-view Omnidreams rollout."""

DEFAULT_VIDEO_HEIGHT = 704
"""Default pixel-space height for HDMap and first-frame inputs."""

DEFAULT_VIDEO_WIDTH = 1280
"""Default pixel-space width for HDMap and first-frame inputs."""

DEFAULT_NUM_CHUNKS = 60
"""Default number of autoregressive chunks generated by a headless rollout."""

DEFAULT_ARTIFACT_PATH = Path("outputs/omnidreams.mp4")
"""Default video artifact path for direct application construction."""

EXAMPLE_DATA_HF_REPO = "nvidia/omni-dreams-samples"
"""Hugging Face dataset containing single-view HDMap clips and first frames."""

EXAMPLE_DATA_HF_BROWSER_URL = (
    "https://huggingface.co/datasets/nvidia/omni-dreams-samples/tree/main/"
    "data/single_view"
)
"""Browser URL listing the available single-view example UUIDs."""

DEFAULT_EXAMPLE_DATA_UUID = "239560dc-33d1-11ef-9720-00044bcbccac"
"""Default bundled single-view scene UUID."""


@dataclass(kw_only=True)
class OmnidreamsInferenceRuntimeConfig(
    InferenceRuntimeConfig["OmnidreamsInferenceRuntime"]
):
    """Configuration for the runtime used by the headless CLI."""

    _target: type[OmnidreamsInferenceRuntime] = field(
        default_factory=lambda: OmnidreamsInferenceRuntime
    )

    device: str = "cuda"
    """Device receiving the fully constructed inference pipeline."""


class OmnidreamsInferenceRuntime(InferenceRuntime[InferenceSession]):
    """Own an Omnidreams pipeline on the configured inference device."""

    _pipeline: OmnidreamsPipeline
    """Pipeline narrowed to the integration type after construction."""

    def __init__(self, config: OmnidreamsInferenceRuntimeConfig) -> None:
        """Construct and place the configured Omnidreams pipeline.

        Args:
            config: Pipeline, session, and device configuration.

        Raises:
            TypeError: The pipeline config does not construct Omnidreams.
        """
        super().__init__(config)
        if not isinstance(self._pipeline, OmnidreamsPipeline):
            raise TypeError(
                "OmnidreamsInferenceRuntime requires an OmnidreamsPipeline; "
                f"got {type(self._pipeline).__name__}"
            )
        device = f"cuda:{self._local_rank}" if self._world_size > 1 else config.device
        self._pipeline = self._pipeline.to(device).eval()

    def warmup(self) -> None:
        """Complete the optional warmup hook without a synthetic rollout."""


@dataclass(kw_only=True)
class OmnidreamsHeadlessConfig(
    VideoOutputApplicationConfig[RuntimeT], Generic[RuntimeT]
):
    """Configuration for a headless HDMap-conditioned application."""

    _target: type[OmnidreamsHeadless] = field(
        default_factory=lambda: OmnidreamsHeadless
    )

    hdmap_path: str | Path | None = None
    """HDMap video; required unless bundled example data supplies it."""

    first_frame_path: str | Path | None = None
    """Initial RGB image or video; required unless example data supplies it."""

    example_data: bool = False
    """Download bundled inputs for any path that is not configured."""

    example_data_uuid: str = DEFAULT_EXAMPLE_DATA_UUID
    """Bundled single-view scene UUID selected when ``example_data`` is enabled."""

    artifact_path: str | Path = DEFAULT_ARTIFACT_PATH
    """Destination written by the video output handler."""

    text_prompt: str = DEFAULT_TEXT_PROMPT
    """Positive prompt applied to the generated driving scene."""

    negative_text_prompt: str = NEGATIVE_PROMPT
    """Negative prompt used for classifier-free guidance."""

    num_frames: int | None = None
    """Exact generated frame count; mutually exclusive with ``num_chunks``."""

    num_chunks: int | None = DEFAULT_NUM_CHUNKS
    """Exact generated chunk count; defaults to ``DEFAULT_NUM_CHUNKS``."""

    pixel_height: int = DEFAULT_VIDEO_HEIGHT
    """Resize target height for HDMap videos and first-frame images."""

    pixel_width: int = DEFAULT_VIDEO_WIDTH
    """Resize target width for HDMap videos and first-frame images."""


class OmnidreamsHeadless(VideoOutputApplication[RuntimeT], Generic[RuntimeT]):
    """Run Omnidreams from an HDMap video and write generated video output."""

    def __init__(
        self,
        config: OmnidreamsHeadlessConfig[RuntimeT],
    ) -> None:
        """Initialize all input, conditioning, inference, and output components.

        Args:
            config: Runtime and application-facing rollout configuration.

        Raises:
            ValueError: The rollout limit or raw global condition is invalid.
        """
        _validate_generation_limit(config.num_frames, config.num_chunks)
        hdmap_path, first_frame_path = _resolve_input_paths(config)
        config.hdmap_path = hdmap_path
        config.first_frame_path = first_frame_path
        super().__init__(config, _placeholder_global_condition())

        pipeline = self._inference_runtime._pipeline
        if not isinstance(pipeline, OmnidreamsPipeline):
            raise TypeError(
                "OmnidreamsHeadless requires an OmnidreamsPipeline; "
                f"got {type(pipeline).__name__}"
            )
        first_frame_image = _load_first_frame(
            first_frame_path,
            pixel_height=config.pixel_height,
            pixel_width=config.pixel_width,
            device=pipeline.device,
            dtype=pipeline.diffusion_model.dtype,
        )
        self.handle_global_condition(
            RawGlobalCondition(
                text_prompt=config.text_prompt,
                negative_text_prompt=config.negative_text_prompt,
                first_frame_image=first_frame_image,
            )
        )
        pipeline.release_oneshot_encoders()

    def _initialize_global_condition_handler(
        self, config: ApplicationConfig[RuntimeT]
    ) -> GlobalConditionHandler:
        """Construct the raw-condition embedding handler for the pipeline.

        Args:
            config: Application configuration accepted for the base hook contract.

        Returns:
            Handler backed by the runtime pipeline's one-shot encoders.

        Raises:
            TypeError: The configured runtime does not own an Omnidreams pipeline.
        """
        del config
        pipeline = self._inference_runtime._pipeline
        if not isinstance(pipeline, OmnidreamsPipeline):
            raise TypeError(
                "OmnidreamsHeadless requires an OmnidreamsPipeline; "
                f"got {type(pipeline).__name__}"
            )
        return OmnidreamsGlobalConditionHandler(pipeline)

    def _initialize_user_input_handler(
        self, config: ApplicationConfig[RuntimeT]
    ) -> UserInputHandler:
        """Construct the HDMap input handler for the Omnidreams pipeline.

        Args:
            config: Application configuration accepted for the base hook contract.

        Returns:
            Handler that yields correctly sized HDMap chunks on the pipeline device.

        Raises:
            TypeError: The application was not given headless configuration, or the
                configured runtime does not own an Omnidreams pipeline.
        """
        if not isinstance(config, OmnidreamsHeadlessConfig):
            raise TypeError(
                "OmnidreamsHeadless requires OmnidreamsHeadlessConfig; "
                f"got {type(config).__name__}"
            )
        if config.hdmap_path is None:
            raise ValueError("OmnidreamsHeadless requires an HDMap path")
        pipeline = self._inference_runtime._pipeline
        if not isinstance(pipeline, OmnidreamsPipeline):
            raise TypeError(
                "OmnidreamsHeadless requires an OmnidreamsPipeline; "
                f"got {type(pipeline).__name__}"
            )
        return HDMapInputHandler(
            config.hdmap_path,
            get_num_frames=pipeline.get_num_frames,
            num_frames=config.num_frames,
            num_chunks=config.num_chunks,
            pixel_height=config.pixel_height,
            pixel_width=config.pixel_width,
            device=pipeline.device,
            dtype=pipeline.diffusion_model.dtype,
        )


def download_single_view_example_data(uuid: str) -> tuple[Path, Path]:
    """Download the HDMap video and first frame for one example UUID.

    Args:
        uuid: UUID of a scene under the dataset's ``data/single_view`` directory.

    Returns:
        Local cached paths to the HDMap video and first-frame image.

    Raises:
        FileNotFoundError: The UUID contains no HDMap video.
        RuntimeError: The UUID contains more than one HDMap video.
    """
    from huggingface_hub import HfApi, hf_hub_download
    from huggingface_hub.hf_api import RepoFile

    subdir = f"data/single_view/{uuid}"
    entries = HfApi().list_repo_tree(
        repo_id=EXAMPLE_DATA_HF_REPO,
        repo_type="dataset",
        path_in_repo=subdir,
        recursive=False,
    )
    files = [entry.path for entry in entries if isinstance(entry, RepoFile)]
    hdmap_candidates = [path for path in files if path.endswith("_hdmap.mp4")]
    if not hdmap_candidates:
        raise FileNotFoundError(
            f"No '*_hdmap.mp4' under {subdir!r} in Hugging Face dataset "
            f"{EXAMPLE_DATA_HF_REPO!r}. Pick a UUID listed at "
            f"{EXAMPLE_DATA_HF_BROWSER_URL} via --example-data-uuid, or supply "
            "--hdmap-path and --first-frame-path explicitly."
        )
    if len(hdmap_candidates) > 1:
        raise RuntimeError(
            f"Multiple '*_hdmap.mp4' files under {subdir!r} in "
            f"{EXAMPLE_DATA_HF_REPO!r}: {hdmap_candidates}."
        )

    hdmap_path = Path(
        hf_hub_download(
            repo_id=EXAMPLE_DATA_HF_REPO,
            repo_type="dataset",
            filename=hdmap_candidates[0],
        )
    )
    first_frame_path = Path(
        hf_hub_download(
            repo_id=EXAMPLE_DATA_HF_REPO,
            repo_type="dataset",
            filename=f"{subdir}/first_frame.png",
        )
    )
    return hdmap_path, first_frame_path


def _resolve_input_paths(
    config: OmnidreamsHeadlessConfig,
) -> tuple[Path, Path]:
    """Resolve explicit or bundled HDMap and first-frame inputs.

    Args:
        config: Headless application configuration containing input selection.

    Returns:
        Resolved HDMap and first-frame paths.

    Raises:
        ValueError: Either path is missing while example data is disabled.
    """
    hdmap_path = config.hdmap_path
    first_frame_path = config.first_frame_path
    if config.example_data and (hdmap_path is None or first_frame_path is None):
        example_hdmap_path, example_first_frame_path = (
            download_single_view_example_data(config.example_data_uuid)
        )
        hdmap_path = hdmap_path or example_hdmap_path
        first_frame_path = first_frame_path or example_first_frame_path

    if hdmap_path is None or first_frame_path is None:
        missing = [
            name
            for name, path in (
                ("--hdmap-path", hdmap_path),
                ("--first-frame-path", first_frame_path),
            )
            if path is None
        ]
        raise ValueError(
            f"{', '.join(missing)} must be supplied unless example_data is enabled"
        )
    return Path(hdmap_path), Path(first_frame_path)


def _validate_generation_limit(num_frames: int | None, num_chunks: int | None) -> None:
    """Validate that exactly one positive rollout limit is configured."""
    if (num_frames is None) == (num_chunks is None):
        raise ValueError("exactly one of num_frames or num_chunks must be configured")
    for name, value in (("num_frames", num_frames), ("num_chunks", num_chunks)):
        if value is not None and (
            isinstance(value, bool) or not isinstance(value, int) or value <= 0
        ):
            raise ValueError(f"{name} must be a positive integer; got {value!r}")


def _headless_config_names() -> tuple[str, ...]:
    """Return shipped single-view pipeline names supported by this application."""
    return tuple(
        sorted(
            name
            for name, config in OMNIDREAMS_CONFIGS.items()
            if isinstance(config.diffusion_model.transformer, CosmosTransformerConfig)
            and config.diffusion_model.transformer.num_views == 1
        )
    )


def _parse_bool(value: str) -> bool:
    """Parse a command-line boolean accepted as an explicit value."""
    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise argparse.ArgumentTypeError(f"expected a boolean value, got {value!r}")


def build_parser() -> argparse.ArgumentParser:
    """Build the ``omnidreams-headless`` command-line parser."""
    parser = argparse.ArgumentParser(
        prog="omnidreams-headless",
        description=(
            "Run a single-view Omnidreams rollout from an HDMap video and "
            "write the generated frames to a video artifact."
        ),
    )
    parser.add_argument(
        "--config",
        required=True,
        choices=_headless_config_names(),
        help="Shipped single-view pipeline configuration to run.",
    )
    parser.add_argument(
        "--artifact-path",
        type=Path,
        help="Destination video artifact path; defaults to outputs/<config>.mp4.",
    )
    parser.add_argument(
        "--hdmap-path",
        type=Path,
        help="HDMap video consumed one inference chunk at a time.",
    )
    parser.add_argument(
        "--first-frame-path",
        type=Path,
        help=(
            "Initial RGB image or video. Video inputs use their first frame and "
            "must match the HDMap resolution."
        ),
    )
    parser.add_argument(
        "--example-data",
        nargs="?",
        const=True,
        default=False,
        type=_parse_bool,
        help="Download bundled inputs for paths that were not supplied.",
    )
    parser.add_argument(
        "--example-data-uuid",
        default=DEFAULT_EXAMPLE_DATA_UUID,
        help="Bundled single-view scene UUID.",
    )
    parser.add_argument(
        "--text-prompt",
        default=DEFAULT_TEXT_PROMPT,
        help="Positive text prompt for the generated driving scene.",
    )
    parser.add_argument(
        "--negative-text-prompt",
        default=NEGATIVE_PROMPT,
        help="Negative text prompt for classifier-free guidance.",
    )
    parser.add_argument(
        "--device",
        default="cuda",
        help="Inference device; defaults to cuda.",
    )

    parser.add_argument(
        "--pixel-height",
        type=int,
        default=DEFAULT_VIDEO_HEIGHT,
        help=f"Input resize height; defaults to {DEFAULT_VIDEO_HEIGHT}.",
    )
    parser.add_argument(
        "--pixel-width",
        type=int,
        default=DEFAULT_VIDEO_WIDTH,
        help=f"Input resize width; defaults to {DEFAULT_VIDEO_WIDTH}.",
    )

    rollout_limit = parser.add_mutually_exclusive_group()
    rollout_limit.add_argument(
        "--num-frames",
        type=int,
        help="Exact frame count ending on an autoregressive chunk boundary.",
    )
    rollout_limit.add_argument(
        "--num-chunks",
        "--total-blocks",
        dest="num_chunks",
        type=int,
        help=(
            "Exact number of autoregressive chunks to generate; defaults to "
            f"{DEFAULT_NUM_CHUNKS} when neither rollout limit is provided."
        ),
    )
    return parser


def _load_first_frame(
    path: Path,
    *,
    pixel_height: int,
    pixel_width: int,
    device: torch.device,
    dtype: torch.dtype,
) -> torch.Tensor:
    """Load one normalized first frame in ``[1, 1, 1, 3, H, W]`` layout."""
    frame = load_first_frame_tensor(
        path,
        pixel_height=pixel_height,
        pixel_width=pixel_width,
        device=device,
        dtype=dtype,
        allow_video=True,
        install_hint=DEFAULT_RUNNER_INSTALL_HINT,
    )
    return frame.unsqueeze(1).unsqueeze(1)


def _placeholder_global_condition() -> InferenceGlobalCondition:
    """Build the temporary condition replaced before the application runs."""
    return InferenceGlobalCondition(
        text_embeddings=torch.empty(1, 1, 1, 1),
        image_embeddings=torch.empty(1, 1, 1, 1, 1, 1),
    )


def _run_from_args(args: argparse.Namespace) -> None:
    """Construct and run the headless application from parsed arguments."""
    artifact_path = args.artifact_path or Path("outputs") / f"{args.config}.mp4"
    num_chunks = args.num_chunks
    if args.num_frames is None and num_chunks is None:
        num_chunks = DEFAULT_NUM_CHUNKS

    pipeline_config = copy.deepcopy(OMNIDREAMS_CONFIGS[args.config])
    runtime_config = OmnidreamsInferenceRuntimeConfig(
        pipeline=pipeline_config,
        session_type=InferenceSession,
        device=args.device,
    )
    application_config = OmnidreamsHeadlessConfig(
        inference_runtime=runtime_config,
        artifact_path=artifact_path,
        hdmap_path=args.hdmap_path,
        first_frame_path=args.first_frame_path,
        example_data=args.example_data,
        example_data_uuid=args.example_data_uuid,
        text_prompt=args.text_prompt,
        negative_text_prompt=args.negative_text_prompt,
        num_frames=args.num_frames,
        num_chunks=num_chunks,
        pixel_height=args.pixel_height,
        pixel_width=args.pixel_width,
    )
    application = OmnidreamsHeadless(application_config)
    application.run()


def main(argv: Sequence[str] | None = None) -> int:
    """Parse command-line arguments and run the headless application.

    Args:
        argv: Optional explicit arguments; ``None`` reads from ``sys.argv``.

    Returns:
        Process exit status.
    """
    args = build_parser().parse_args(argv)
    _run_from_args(args)
    return 0


__all__ = [
    "DEFAULT_ARTIFACT_PATH",
    "DEFAULT_EXAMPLE_DATA_UUID",
    "DEFAULT_NUM_CHUNKS",
    "DEFAULT_TEXT_PROMPT",
    "DEFAULT_VIDEO_HEIGHT",
    "DEFAULT_VIDEO_WIDTH",
    "OmnidreamsHeadless",
    "OmnidreamsHeadlessConfig",
    "OmnidreamsInferenceRuntime",
    "OmnidreamsInferenceRuntimeConfig",
    "build_parser",
    "main",
]


if __name__ == "__main__":
    raise SystemExit(main())
